/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as TerapieRouteImport } from './routes/terapie'
import { Route as StoricoReportRouteImport } from './routes/storico-report'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScorteRouteImport } from './routes/scorte'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistratiRouteImport } from './routes/registrati'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PazienteRouteImport } from './routes/paziente'
import { Route as NotificheRouteImport } from './routes/notifiche'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeMieTerapieRouteImport } from './routes/le-mie-terapie'
import { Route as ImpostazioniRouteImport } from './routes/impostazioni'
import { Route as GuidaPubblicaRouteImport } from './routes/guida-pubblica'
import { Route as GuidaRouteImport } from './routes/guida'
import { Route as EccezioniRouteImport } from './routes/eccezioni'
import { Route as DoseDaConfermareRouteImport } from './routes/dose-da-confermare'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PazientiIndexRouteImport } from './routes/pazienti.index'
import { Route as PazientiIdRouteImport } from './routes/pazienti.$id'

const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapieRoute = TerapieRouteImport.update({
  id: '/terapie',
  path: '/terapie',
  getParentRoute: () => rootRouteImport,
} as any)
const StoricoReportRoute = StoricoReportRouteImport.update({
  id: '/storico-report',
  path: '/storico-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorteRoute = ScorteRouteImport.update({
  id: '/scorte',
  path: '/scorte',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistratiRoute = RegistratiRouteImport.update({
  id: '/registrati',
  path: '/registrati',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PazienteRoute = PazienteRouteImport.update({
  id: '/paziente',
  path: '/paziente',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificheRoute = NotificheRouteImport.update({
  id: '/notifiche',
  path: '/notifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeMieTerapieRoute = LeMieTerapieRouteImport.update({
  id: '/le-mie-terapie',
  path: '/le-mie-terapie',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniRoute = ImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidaPubblicaRoute = GuidaPubblicaRouteImport.update({
  id: '/guida-pubblica',
  path: '/guida-pubblica',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidaRoute = GuidaRouteImport.update({
  id: '/guida',
  path: '/guida',
  getParentRoute: () => rootRouteImport,
} as any)
const EccezioniRoute = EccezioniRouteImport.update({
  id: '/eccezioni',
  path: '/eccezioni',
  getParentRoute: () => rootRouteImport,
} as any)
const DoseDaConfermareRoute = DoseDaConfermareRouteImport.update({
  id: '/dose-da-confermare',
  path: '/dose-da-confermare',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PazientiIndexRoute = PazientiIndexRouteImport.update({
  id: '/pazienti/',
  path: '/pazienti/',
  getParentRoute: () => rootRouteImport,
} as any)
const PazientiIdRoute = PazientiIdRouteImport.update({
  id: '/pazienti/$id',
  path: '/pazienti/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/cookie': typeof CookieRoute
  '/dose-da-confermare': typeof DoseDaConfermareRoute
  '/eccezioni': typeof EccezioniRoute
  '/guida': typeof GuidaRoute
  '/guida-pubblica': typeof GuidaPubblicaRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/le-mie-terapie': typeof LeMieTerapieRoute
  '/login': typeof LoginRoute
  '/notifiche': typeof NotificheRoute
  '/paziente': typeof PazienteRoute
  '/privacy': typeof PrivacyRoute
  '/registrati': typeof RegistratiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scorte': typeof ScorteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/storico-report': typeof StoricoReportRoute
  '/terapie': typeof TerapieRoute
  '/termini': typeof TerminiRoute
  '/pazienti/$id': typeof PazientiIdRoute
  '/pazienti/': typeof PazientiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/cookie': typeof CookieRoute
  '/dose-da-confermare': typeof DoseDaConfermareRoute
  '/eccezioni': typeof EccezioniRoute
  '/guida': typeof GuidaRoute
  '/guida-pubblica': typeof GuidaPubblicaRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/le-mie-terapie': typeof LeMieTerapieRoute
  '/login': typeof LoginRoute
  '/notifiche': typeof NotificheRoute
  '/paziente': typeof PazienteRoute
  '/privacy': typeof PrivacyRoute
  '/registrati': typeof RegistratiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scorte': typeof ScorteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/storico-report': typeof StoricoReportRoute
  '/terapie': typeof TerapieRoute
  '/termini': typeof TerminiRoute
  '/pazienti/$id': typeof PazientiIdRoute
  '/pazienti': typeof PazientiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/cookie': typeof CookieRoute
  '/dose-da-confermare': typeof DoseDaConfermareRoute
  '/eccezioni': typeof EccezioniRoute
  '/guida': typeof GuidaRoute
  '/guida-pubblica': typeof GuidaPubblicaRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/le-mie-terapie': typeof LeMieTerapieRoute
  '/login': typeof LoginRoute
  '/notifiche': typeof NotificheRoute
  '/paziente': typeof PazienteRoute
  '/privacy': typeof PrivacyRoute
  '/registrati': typeof RegistratiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scorte': typeof ScorteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/storico-report': typeof StoricoReportRoute
  '/terapie': typeof TerapieRoute
  '/termini': typeof TerminiRoute
  '/pazienti/$id': typeof PazientiIdRoute
  '/pazienti/': typeof PazientiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caregiver'
    | '/cookie'
    | '/dose-da-confermare'
    | '/eccezioni'
    | '/guida'
    | '/guida-pubblica'
    | '/impostazioni'
    | '/le-mie-terapie'
    | '/login'
    | '/notifiche'
    | '/paziente'
    | '/privacy'
    | '/registrati'
    | '/reset-password'
    | '/scorte'
    | '/sitemap.xml'
    | '/storico-report'
    | '/terapie'
    | '/termini'
    | '/pazienti/$id'
    | '/pazienti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caregiver'
    | '/cookie'
    | '/dose-da-confermare'
    | '/eccezioni'
    | '/guida'
    | '/guida-pubblica'
    | '/impostazioni'
    | '/le-mie-terapie'
    | '/login'
    | '/notifiche'
    | '/paziente'
    | '/privacy'
    | '/registrati'
    | '/reset-password'
    | '/scorte'
    | '/sitemap.xml'
    | '/storico-report'
    | '/terapie'
    | '/termini'
    | '/pazienti/$id'
    | '/pazienti'
  id:
    | '__root__'
    | '/'
    | '/caregiver'
    | '/cookie'
    | '/dose-da-confermare'
    | '/eccezioni'
    | '/guida'
    | '/guida-pubblica'
    | '/impostazioni'
    | '/le-mie-terapie'
    | '/login'
    | '/notifiche'
    | '/paziente'
    | '/privacy'
    | '/registrati'
    | '/reset-password'
    | '/scorte'
    | '/sitemap.xml'
    | '/storico-report'
    | '/terapie'
    | '/termini'
    | '/pazienti/$id'
    | '/pazienti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaregiverRoute: typeof CaregiverRoute
  CookieRoute: typeof CookieRoute
  DoseDaConfermareRoute: typeof DoseDaConfermareRoute
  EccezioniRoute: typeof EccezioniRoute
  GuidaRoute: typeof GuidaRoute
  GuidaPubblicaRoute: typeof GuidaPubblicaRoute
  ImpostazioniRoute: typeof ImpostazioniRoute
  LeMieTerapieRoute: typeof LeMieTerapieRoute
  LoginRoute: typeof LoginRoute
  NotificheRoute: typeof NotificheRoute
  PazienteRoute: typeof PazienteRoute
  PrivacyRoute: typeof PrivacyRoute
  RegistratiRoute: typeof RegistratiRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScorteRoute: typeof ScorteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoricoReportRoute: typeof StoricoReportRoute
  TerapieRoute: typeof TerapieRoute
  TerminiRoute: typeof TerminiRoute
  PazientiIdRoute: typeof PazientiIdRoute
  PazientiIndexRoute: typeof PazientiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapie': {
      id: '/terapie'
      path: '/terapie'
      fullPath: '/terapie'
      preLoaderRoute: typeof TerapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storico-report': {
      id: '/storico-report'
      path: '/storico-report'
      fullPath: '/storico-report'
      preLoaderRoute: typeof StoricoReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorte': {
      id: '/scorte'
      path: '/scorte'
      fullPath: '/scorte'
      preLoaderRoute: typeof ScorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrati': {
      id: '/registrati'
      path: '/registrati'
      fullPath: '/registrati'
      preLoaderRoute: typeof RegistratiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paziente': {
      id: '/paziente'
      path: '/paziente'
      fullPath: '/paziente'
      preLoaderRoute: typeof PazienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifiche': {
      id: '/notifiche'
      path: '/notifiche'
      fullPath: '/notifiche'
      preLoaderRoute: typeof NotificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-mie-terapie': {
      id: '/le-mie-terapie'
      path: '/le-mie-terapie'
      fullPath: '/le-mie-terapie'
      preLoaderRoute: typeof LeMieTerapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni': {
      id: '/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof ImpostazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guida-pubblica': {
      id: '/guida-pubblica'
      path: '/guida-pubblica'
      fullPath: '/guida-pubblica'
      preLoaderRoute: typeof GuidaPubblicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guida': {
      id: '/guida'
      path: '/guida'
      fullPath: '/guida'
      preLoaderRoute: typeof GuidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eccezioni': {
      id: '/eccezioni'
      path: '/eccezioni'
      fullPath: '/eccezioni'
      preLoaderRoute: typeof EccezioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dose-da-confermare': {
      id: '/dose-da-confermare'
      path: '/dose-da-confermare'
      fullPath: '/dose-da-confermare'
      preLoaderRoute: typeof DoseDaConfermareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazienti/': {
      id: '/pazienti/'
      path: '/pazienti'
      fullPath: '/pazienti/'
      preLoaderRoute: typeof PazientiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazienti/$id': {
      id: '/pazienti/$id'
      path: '/pazienti/$id'
      fullPath: '/pazienti/$id'
      preLoaderRoute: typeof PazientiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaregiverRoute: CaregiverRoute,
  CookieRoute: CookieRoute,
  DoseDaConfermareRoute: DoseDaConfermareRoute,
  EccezioniRoute: EccezioniRoute,
  GuidaRoute: GuidaRoute,
  GuidaPubblicaRoute: GuidaPubblicaRoute,
  ImpostazioniRoute: ImpostazioniRoute,
  LeMieTerapieRoute: LeMieTerapieRoute,
  LoginRoute: LoginRoute,
  NotificheRoute: NotificheRoute,
  PazienteRoute: PazienteRoute,
  PrivacyRoute: PrivacyRoute,
  RegistratiRoute: RegistratiRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScorteRoute: ScorteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoricoReportRoute: StoricoReportRoute,
  TerapieRoute: TerapieRoute,
  TerminiRoute: TerminiRoute,
  PazientiIdRoute: PazientiIdRoute,
  PazientiIndexRoute: PazientiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
